# Generated by Django 3.1.4 on 2020-12-21 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comments_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
